### ISSUE TITLE
Failed to retrieve a connection pool from the hashring

### ISSUE THREAD

**Issue by swynter-ladbrokes** [SalesforceEng/rmux#19] opened 2016-07-14 00:05 UTC
Configuration:

200 php-fpm processes
1 rmux

```json
[
	{
		"socket": "/tmp/rmux.sock",
		"poolSize" : 50,

		"tcpConnections": ["10.36.1.100:32888","10.36.1.117:32930","10.36.1.120:32799","10.36.1.121:32871","10.36.1.98:32849","10.36.5.64:32937","10.36.5.70:32865","10.36.5.83:32793"],

		"remoteConnectTimeout": 5
	}
]
```

Is this a sign our connection pool is too small?

**Comment by mikemfrank** [comment] 2016-07-14 16:07
It looks like this happens before we try to get a connection from the pool, so I doubt that the size of the pool is the issue.  My guess is that all of the configured redis instances are unreachable, perhaps due to a networking issue on the host running rmux.

**Comment by asuahsahua** [comment] 2016-07-14 16:37
It could also be that the instance that it is trying to hit for a given key
is down, I would recommend putting the pool into failover mode if that fits
your use case.

Sent from my iPhone

On Jul 14, 2016, at 9:07 AM, Michael Frank <notifications@github.com> wrote:

It looks like this happens before we try to get a connection from the pool,
so I doubt that the size of the pool is the issue. My guess is that all of
the configured redis instances are unreachable, perhaps due to a networking
issue on the host running rmux.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SalesforceEng/rmux/issues/19#issuecomment-232712027>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA6Zu1r03YpxL-HCGUcDOCE2T_yoh9Z1ks5qVl6tgaJpZM4JL94o>
.

**Comment by swynter-ladbrokes** [comment] 2016-07-17 22:41
I should expand on the issue given your feedback.

1 container is 200 php-fpm processes, 1 rmux.
There are 30 container running across the network

There are the (as listed) 8 redis 3.0.3 servers (which all function and are reachable anywhere within the network). They basically should never be down (ideal scenario)

The reason we're trying rmux is we're having connection issues that we've tried about everything to resolve. We've put it down to 30 * 200 (6000) php-fpms trying to make their own connections to the 8 servers. Phpredis has been ever useful with it's one error for all "redis server has gone away" in some instances, and in others the connection times out after 30s

Our hope was to drop rmux in place, have it manage the connection pool (figuring 50'd be enough) and point php-fpm at it.

In testing that works fine, in production it was a totally different story.

**Comment by swynter-ladbrokes** [comment] 2016-07-18 02:43
Sorry, I think I've solved it, I read "remoteConnectTimeout": 5 as being 5 seconds, not 5ms (pay attention to application startup)

It's quite evident that under the load of all our web traffic the 5ms is an easily reached target - change it to 500 and that problem goes away.

**Comment by mikemfrank** [comment] 2016-07-20 12:44
Glad to hear you found the cause!  I'm going to close this one out.

**Closed by mikemfrank** 2016-07-20 12:44 UTC
